name: Ruff
on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - name: Install Ruff
      run: pip install ruff
    - name: Run Ruff with auto-fix
      run: ruff check . --fix  # Use `ruff check` with the `--fix` argument to auto-fix
    - name: Commit changes if there are any
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'style fixes by ruff'
        file_pattern: '*.py'